name: ai-agent-askus
channels:
  - defaults
  - conda-forge
  - akode
  - xformers
dependencies:
  - python=3.10  
  - neo4j-python-driver
  - scrapy
  - beautifulsoup4
  - lxml
  - ipykernel
  - langgraph
  - langchain
  - langchain-chroma
  - langchain-community
  - scikit-learn
  - datasets
  - sentence-transformers
  - langchain-text-splitters
  - html2text
  - langchain-huggingface
  - xformers
  - pytorch-gpu