name: ai-agent-askus
channels:
  - defaults
  - conda-forge
  - akode
dependencies:
  - scrapy
  - beautifulsoup4
  - lxml
  - ipykernel
  - langgraph
  - langchain
  - langchain-chroma
  - langchain-community
  - scikit-learn
  - datasets
  - sentence-transformers
  - langchain-text-splitters
  - html2text