name: ai-agent-askus
channels:
  - defaults
  - forge
dependencies:
  - scrapy
  - beautifulsoup4
  - lxml
  - ipykernel
  - pip:
      - langchain
      - langchain-experimental
      - sentence-transformers